import{a as v,S,i as n}from"./assets/vendor--6n4cVRZ.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const P="54634417-32a9cc2e653c0a3a9a7b25778",q="https://pixabay.com/api/";async function f(s,r=1){return(await v(q,{params:{key:P,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}const x=new S(".js-gallery a",{captions:!0,captionPosition:"bottom",captionsData:"alt"}),m=document.querySelector(".gallery"),g=document.querySelector(".loader"),p=document.querySelector(".load-more-js");function y(s){const r=s.map(({webformatURL:o,largeImageURL:c,tags:e,likes:t,views:i,comments:L,downloads:b})=>`
        <li class = "img-item">
        <a href = "${c}">
        <img src = "${o}" alt = "${e}" width = 300/>
        </a>
        <div class = "wrapper">
        <h2><span class = "text-weight">Likes</span> ${t}</h2>
        <h2><span class = "text-weight">Views</span> ${i}</h2>
        <h2><span class = "text-weight">Comments</span> ${L}</h2>
        <h2><span class = "text-weight">Downloads</span> ${b}</h2>
        </div>
        </li>
        `).join("");m.insertAdjacentHTML("beforeend",r),x.refresh()}function M(){m.innerHTML=""}function w(){g.classList.remove("blur")}function u(){g.classList.add("blur")}function $(){p.classList.remove("blur")}function d(){p.classList.add("blur")}const O=document.querySelector(".form");let l="",a=1,h=0;u();d();O.addEventListener("submit",R);p.addEventListener("click",B);async function R(s){s.preventDefault();const r=s.target.elements["search-text"].value.trim();if(r){r!==l&&(a=1,M(),d()),l=r,w();try{const o=await f(l,a);if(o.hits.length===0){u(),n.error({message:"Sorry, there are no images matching your search query. Please, try again!",position:"topRight"});return}h=o.totalHits,y(o.hits),a*15<h?$():(d(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),a++}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{u()}}}async function B(){w();try{const s=await f(l,a);y(s.hits);const o=document.querySelector(".img-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"}),a*15>=h&&(d(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),a++}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{u()}}
//# sourceMappingURL=index.js.map
