import{a as S,S as P,i as n}from"./assets/vendor--6n4cVRZ.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const q="54634417-32a9cc2e653c0a3a9a7b25778",x="https://pixabay.com/api/";async function m(s,r=1){return(await S(x,{params:{key:q,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}const M=new P(".js-gallery a",{captions:!0,captionPosition:"bottom",captionsData:"alt"}),f=document.querySelector(".gallery"),g=document.querySelector(".loader"),h=document.querySelector(".load-more-js");function y(s){const r=s.map(({webformatURL:o,largeImageURL:c,tags:e,likes:t,views:i,comments:b,downloads:v})=>`
        <li class = "img-item">
        <a href = "${c}">
        <img src = "${o}" alt = "${e}" width = 300/>
        </a>
        <div class = "wrapper">
        <h2><span class = "text-weight">Likes</span> ${t}</h2>
        <h2><span class = "text-weight">Views</span> ${i}</h2>
        <h2><span class = "text-weight">Comments</span> ${b}</h2>
        <h2><span class = "text-weight">Downloads</span> ${v}</h2>
        </div>
        </li>
        `).join("");f.insertAdjacentHTML("beforeend",r),M.refresh()}function $(){f.innerHTML=""}function w(){g.classList.remove("blur")}function p(){g.classList.add("blur")}function L(){h.classList.remove("blur")}function u(){h.classList.add("blur")}const O=document.querySelector(".form");let d="",a=1,l=0;p();u();O.addEventListener("submit",R);h.addEventListener("click",B);async function R(s){s.preventDefault();const r=s.target.elements["search-text"].value.trim();if(r){a=1,l=0,$(),u(),d=r,w();try{const o=await m(d,a);if(o.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please, try again!",position:"topRight"});return}l=o.totalHits,y(o.hits),a*15<l?L():n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),a++}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{p()}}}async function B(){w(),u();try{const s=await m(d,a);y(s.hits);const o=document.querySelector(".img-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"}),a*15>=l?(u(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):L(),a++}catch{n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{p()}}
//# sourceMappingURL=index.js.map
